/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppTabBar: typeof import('./src/components/shared/navigation/AppTabBar.vue')['default']
    KnowledgeEntryFab: typeof import('./src/components/shared/navigation/KnowledgeEntryFab.vue')['default']
  }
}
